### ISSUE TITLE
Problems launching Threnoscope standalone + threnoscopeSC

### ISSUE THREAD

**Issue by hujairi-zz** [thormagnusson/threnoscopeSC#4]
Hello,

I am really sorry for this trouble.

I currently use macOS 12.1 and SuperCollider 3.12.1. I managed to use Threnoscope back when it was first publicly launched, but recently haven't been able to use it since updating my operating system.

The standalone application (after dealing with the security notification) just results in the SuperCollider icon opening up but freezing. In threnoscopeSC, when I run the ThrenoScope.new(2); command, I can see the threnoscope gui just as a white screen with black borders), and there is no where for me to input the code on the right hand side. 

I wonder if I am doing anything wrong or is there something problematic with my approach?

Many thanks.

**Comment by Etol1LC** [comment]
Hello Hasan, I do not how to help you with the standalone App, but I can
help you out with the ThrenoscopeSC issue.
Try this:

- Install the Threnoscope from my fork of the repository:

Quarks.install("https://github.com/Etol1LC/threnoscopeSC.git");

- Recompile Class Library (always a good thing to do after installing a
Quark).

Then try launch Threnoscope the usual way:

s.boot;
ThrenoScope.new(2);

I have tried to solve the installation issue. This has been tested on Mac
and Windows and hopefully will be merged in the main repo.

Otherwise, If you do not want to install it from my fork, do the following:

- Once installed(from the main repo), open the User Support Directory
- inside the SC folder create one Folder and call it "threnoscope"
- inside threnoscope folder create three subfolders and call them: scl,
scl_user, sample.
- inside the sample folder place an empty file called
"_samples.scd"(include the underscore)
- Recompile the Class Library
- launch Threnoscope: s.boot; ThrenoScope.scd


This should make everything work fine.

Cheers,

Claudio


Il lun 31 gen 2022, 00:02 Hasan Hujairi ***@***.***> ha
scritto:

**Comment by Etol1LC** [comment]
Sorry but the three subfolders should be called: scl, scl_user and samples. 
Not sample. Sorry for the mistake!

**Comment by hujairi-zz** [comment]
@Etol1LC Thanks so much for this! The manual approach (by creating the folders and file) worked great for me. Thanks again for this!

**Comment by Etol1LC** [comment]
No problem at all! Enjoy the Threnoscope!!!

Etol



Il mar 15 feb 2022, 15:28 Hasan Hujairi ***@***.***> ha
scritto:
